routes:
  /:
    data: page.home
    template: home
  /projects/:
    data: tag.projects
    template: projects
  /articles/:
    data: tag.articles
    template: articles

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
