routes:
  /:
    data: page.home
    template: home
  /projects/:
    data: tag.projects
    template: projects
  /articles/:
    data: tag.articles
    template: articles

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: primary_tag:-projects+primary_tag:-articles
  /projects/:
    permalink: /projects/{slug}/
    filter: primary_tag:projects
  /articles/:
    permalink: /articles/{slug}/
    filter: primary_tag:articles

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
